import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Car Racing 3d',
  description: 'Generated by create next app',
  manifest: '/manifest.webmanifest',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="description" content={metadata.description || ''} />
        <link rel="manifest" href={metadata.manifest || ''} />
        <title>{metadata.title}</title>
        {/* Add other meta tags, link tags, etc. here */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
